### ISSUE TITLE
Error dimensions parse in ConvParser()?

### ISSUE THREAD

**Issue by cnjsdfcy** [ZigZag-Project/zigzag#13]
Hi,

As in below code segment, shouldn't the IX = ia_shape[3], IY = ia_shape[2]? Also W/O should be NCHW layout in ONNX.

https://github.com/KULeuven-MICAS/zigzag/blob/de6d4bbecec8cbb1f108ad2ed379ab7cfef01d0a/zigzag/classes/io/onnx/conv.py#L88C1-L94C33

Thanks,
Jason

**Comment by asyms** [comment]
Fixed in https://github.com/KULeuven-MICAS/zigzag/commit/9795495394aadc6390a5528750797413f2525831
