### ISSUE TITLE
Installation page not found.

### ISSUE THREAD

**Issue by russ-spec** [ZigZag-Project/zigzag#16]
Hi, 
In the README.md, the installation link to a non existing page.
https://github.com/KULeuven-MICAS/zigzag/#:~:text=this%20search%20space.-,Installation,-Please%20take%20a
The link should be changed to [https://kuleuven-micas.github.io/zigzag/installation.html](https://kuleuven-micas.github.io/zigzag/installation.html)

**Comment by skarl9** [comment]
I fixed this link in the README.md
