### ISSUE TITLE
Memory overutilization error

### ISSUE THREAD

**Issue by sjoks93** [ZigZag-Project/zigzag#19]
AssertionError: Memory shared by {'I1': 1, 'I2': 1, 'O': 1} (memory operand, memory level) has shared utilization of 1.02569580078125, which is > 1 (memory level starts from 0).

I receive this error when running the temporal search engine using the attached directory and the following command:

python seneca/main.py --model seneca.inputs.workload.resnet_layer1 --accelerator seneca.inputs.hardware.hardware --mapping seneca.inputs.mapping.mapping
[seneca.zip](https://github.com/KULeuven-MICAS/zigzag/files/12240016/seneca.zip)

**Comment by asyms** [comment]
Hi. Thanks for spotting this issue. We hadn't considered your architectural case where only a higher memory level is unrolling an irrelevant output dimension ('C' in your case) which requires partial sum precision. I have fixed it in release 2.4.4.
