### ISSUE TITLE
What do served_dimensions and unrolled count mean exactly in memory_level class?

### ISSUE THREAD

**Issue by keneoneth** [ZigZag-Project/zigzag#36]
I am not sure about what technically served_dimensions and unrolled count mean in the memory level class linked below. Any help will be well appreciated.

https://github.com/KULeuven-MICAS/zigzag/blob/master/zigzag/classes/hardware/architecture/memory_level.py

**Comment by asyms** [comment]
Hi, you can find more information regarding the served dimensions here: https://kuleuven-micas.github.io/zigzag/hardware.html#memory-hierarchy

It specifies how the memory level connects to the lower level(s) in terms of the dimensions of the operational array. If you have more questions after reading the documentation, feel free to ask here!
