### ISSUE TITLE
Getting Started command outdated 

### ISSUE THREAD

**Issue by Victor-Jung** [ZigZag-Project/zigzag#5]
The following command in Getting Stated is outdated:

`python main_onnx.py --model inputs/examples/workloads/alexnet_inferred.onnx --accelerator inputs.examples.hardware.TPU_like --mapping inputs.examples.mapping.alexnet_on_tpu_like`

The name of the hardware and mapping have changed, the correct command is the following (using Eyeriss instead of TPU):

`python main_onnx.py --model inputs/examples/workloads/alexnet_int8_inferred.onnx --accelerator inputs.examples.hardware.Eyeriss_like --mapping inputs.examples.mapping.alexnet_on_eyeriss_like`

Other part of the text in the Getting Started page of the doc need to be updated too.

Best,
Victor

**Comment by asyms** [comment]
Thanks for noting this Victor! The documentation has been updated.
