### ISSUE TITLE
Remove multiplier input precision attribute

### ISSUE THREAD

**Issue by RobinGeens** [ZigZag-Project/zigzag#66]
https://github.com/KULeuven-MICAS/zigzag/blob/907b812b72a49c30e916b6209569edb3792c4184/docs/source/hardware.rst?plain=1#L16

https://github.com/KULeuven-MICAS/zigzag/blob/907b812b72a49c30e916b6209569edb3792c4184/zigzag/inputs/hardware/edge_tpu_like.yaml#L107

As far as I know, the **multiplier input precision** attribute is not used in regular accelerators and should be removed for simplicity. The same can be sad for **adder output precision**. 

It is used in IMC accelerators I think, but in that case it should not be present in the definition of regular accelerators.

**Comment by asyms** [comment]
https://github.com/KULeuven-MICAS/zigzag/pull/71
