### ISSUE TITLE
Why is global_buffer removed? 

### ISSUE THREAD

**Issue by zzczzc20** [ZigZag-Project/zigzag#9]
Hello everyone,
Why do you remove global_buffer in the commit https://github.com/KULeuven-MICAS/zigzag/commit/317ce611914ef87df49798a980c45ac2d171bb46 ?
Thanks!

**Comment by asyms** [comment]
Hi,

This was removed because it was unused. Please keep an eye on the Stream repository (https://github.com/KULeuven-MICAS/stream) where this behavior will be implemented correctly for multi-core architectures.
