### ISSUE TITLE
ModuleNotFoundError: No module named 'zigzag.stages.AcceleratorParserStage'

### ISSUE THREAD

**Issue by ZhangYuanQing99** [ZigZag-Project/zigzag#93]
Hello,

I am trying to run the code, but I encountered the following error:

**ModuleNotFoundError: No module named 'zigzag.stages.AcceleratorParserStage'**

I have installed all the required dependencies as mentioned in the documentation, but the issue persists. Could anyone help me understand why this error is occurring and how I can resolve it?

Thank you!

**Comment by asyms** [comment]
Hi,

Thank you for bringing up this issue. The documentation was not up to date with recent changes. The `main_onnx.py` file is deprecated, and you should use `main.py` instead. A new PR https://github.com/KULeuven-MICAS/zigzag/pull/94 is currently open which fixes the documentation and deletes the `main_onnx.py` completely.

You can already use the `main.py` which should work as intended.
If it doesn't, feel free to open a new issue.

Kind regards,
Arne
